
<?php

/**
 * Theme hook
 */
function rp_product_theme($existing, $type, $theme, $path) {
  return array(
    // Blocks themes
    // ---------------------------------------------------------------------
    'rp_site_products_block' => array(
      'variables' => ['variables' => []],
      'template'  => 'products'
    ),
    'rp_site_product_teaser_block' => array(
      'variables' => ['variables' => []],
      'template'  => 'product_teaser'
    ),
  );
}

