<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

/**
 * Theme hook.
 */
function rp_product_theme($existing, $type, $theme, $path) {
  return [
    // Blocks themes
    // ---------------------------------------------------------------------.
    'rp_site_products_block' => [
      'variables' => ['variables' => []],
      'template'  => 'products',
    ],
    'rp_site_product_teaser_block' => [
      'variables' => ['variables' => []],
      'template'  => 'product_teaser',
    ],
  ];
}
