---
title: button-bubble
name: button-bubble
collection: atoms
---
<div class="button-bubble text-center">
  <div class="spacer spacer-xs"></div>
  <div class="bubble-icon">
    <a aria-label="Lien" href="#"><i class="retraitespopulaires-icon retraitespopulaires-icon-2x retraitespopulaires-icon-lock"></i></a>
  </div>
  <div class="bubble-link">
    <a href="#" class="pretty-link">Lien</a>
  </div>
</div>
