---
title: button-bubble
name: button-bubble
collection: atoms
notes: |
  ##### Usage : `button-bubble`
---
<div class="button-bubble text-center">
  <div class="spacer spacer-xs"></div>
  <div class="bubble-icon">
    <a href="#"><i class="retraitespopulaires-icon retraitespopulaires-icon-2x retraitespopulaires-icon-lock"></i></a>
  </div>
  <div class="bubble-link">
    <a href="#" class="pretty-link">Lien</a>
  </div>
</div>
