---
title: highlight
name: highlight
collection: atoms
notes: |
  ##### Usage : `highlight`
  - **highlight_theme** - <i>String</i> - <b>['assurance'|'prevoyance'|'immobilier'|'hypotheque'|'institutionnel'|'profelia'|'cpev'|'cip']</b>

---
<p>Retraites Populaires est <mark class="text-highlight-{{highlight_theme|default('primary')}}">responsable</mark>. Au coeur de sa raison d’être se trouve le <mark class="text-highlight-{{highlight_theme|default('primary')}}">respect des engagements</mark>.</p>
