---
title: icon-text
name: icon-text
collection: atoms
notes: |
  ##### Usage : `icon-text`
---
<div class="icon-text icon-text-center">
  <a href="#0" class="retraitespopulaires-icon retraitespopulaires-icon retraitespopulaires-icon-arrow-left no-underline"></a>
  <div class="icon-text-txt">
    <a href="/contact/questions-reponses" class="pretty-link">Retour aux questions et réponses</a>
  </div>
</div>
