---
title: Input Select
name: input-select
collection: atoms
notes: |
  Can be wrapped in `.theme-[theme]` to change look.
---
<div class="form-group">
  <label for="inputID">Label</label>
  <select class="form-control form-control-{{ input_select_theme }}">
    <option>Choisir, c'est renoncer...</option>
    <option>The second option</option>
    <option>The third option</option>
  </select>
  </div>
