---
title: input-checkbox
name: input-checkbox
notes: |
  Can be wrapped in `.theme-[theme]` to change look.
collection: atoms
---
<div class="form-group">
  <div class="input-checkbox">
    <input type="checkbox" id="meringue" value="meringue-crème-double">
    <label for="meringue">Meringue crème double</label>
  </div>
  <div class="input-checkbox">
    <input type="checkbox" id="miel" value="miel" checked>
    <label for="miel">Miel</label>
  </div>
</div>
