---
title: input-file
name: input-file
changes:
  3.0.0: Improvements to CSS, the `.label` class became `.form-control-label`.
collection: atoms
---
<div class="form-group form-file">
  <span class="form-control-label">Certificat de salaire</span>
  <div class="form-file-handler btn btn-lg btn-primary">
    <label for="inputID">Télécharger votre fichier</label>
    <input id="inputID" type="file"></input>
  </div>
</div>
