---
title: teaser-product
name: teaser-product
collection: atoms
notes: |
  ##### Usage : `teaser-product`
---
<div class="teaser-product shadow shadow-down">
  <div class="product-heading">
    <div class="product-title h1"><div class="product-prefix">RP</div> Rentes immédiate</div>
  </div>
  <p class="product-body">Profitez de votre retraite! Placez un capital de manière sûre et bénéficiez tout de suite de rentes à vie.</p>
</div>
