env:
  browser: true
  es6: true
extends: "eslint:recommended"
ecmaFeatures:
  blockBindings: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - VariableDeclarator: { "var": 2, "let": 2, "const": 3 }
  linebreak-style:
    - error
    - unix
  no-var: 2
  semi:
    - error
    - always
  no-console: 0
globals:
  jQuery: false
  drupalSettings: false
  google: false
  PhotoSwipe: false
  PhotoSwipeUI_Default: false
