<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function rp_contact_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['field_popin']) && isset($form['field_email_popin'])) {
    $form['field_email_popin']['#states'] = [
      'visible' => [
        ':input[name="field_popin[value]"]' => ['checked' => TRUE],
      ],
    ];

    $receivers = Drupal::state()->get('rp_contact.settings.popin')['receivers'];
    // TODO fix this, it doesn't work, I must be missing something.
    $form['field_email_popin']['widget'][0]['value']['#placeholder'] = $receivers;
  }
}

/**
 * Theme hook.
 */
function rp_contact_theme($existing, $type, $theme, $path) {
  return [
    // Blocks themes
    // ---------------------------------------------------------------------.
    'rp_contact_contact_attachment_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_attachment',
    ],
    'rp_contact_contact_cta_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_cta',
    ],
    'rp_contact_contact_teaser_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_teaser',
    ],
    'rp_contact_contact_teaser_detail_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_teaser_detail',
    ],
    'rp_contact_advisors_collection_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_advisors_collection',
    ],
    'rp_contact_contacts_collection_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_contacts_collection',
    ],
    'rp_contact_popin_block' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/contact_popin',
    ],

    // Pages themes
    // ---------------------------------------------------------------------.
    'rp_contact_search_zip_page' => [
      'variables' => ['variables' => []],
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'pages/search_zip',
    ],
  ];
}

require_once 'src/Mail/mails.php';
