
<?php

/**
* Theme hook
*/
function rp_site_theme($existing, $type, $theme, $path) {
    return array(
        // Blocks themes
        // ---------------------------------------------------------------------
        'rp_site_documents_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/documents'
        ),
        'rp_site_faqs_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/faqs'
        ),
        'rp_site_contact_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/contact'
        ),
        'rp_site_advisor_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/advisor'
        ),

        // Pages themes
        // ---------------------------------------------------------------------
        'rp_site_documents_page' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'pages/documents'
        ),
        'rp_site_faqs_page' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'pages/faqs'
        ),
    );
}
