<?php

/**
* Theme hook
*/
function rp_homepage_theme($existing, $type, $theme, $path) {
  return array(
    // Blocks themes
    // ---------------------------------------------------------------------
    'rp_homepage_blocks' => array(
        // Use the following syntax to retrieve all variables in the "variables" container
        'variables' => ['variables' => []],
        // Set the template attribute to force the theme suggestions into a sub folder
        // using [template].html.twig
        'path' => 'themes/retraitespopulaires' . '/templates/' . $theme,
        'template'  => 'blocks/rp--homepage--blocks'
    ),
    'rp_homepage_highlight' => array(
      // Use the following syntax to retrieve all variables in the "variables" container
      'variables' => ['variables' => []],
      // Set the template attribute to force the theme suggestions into a sub folder
      // using [template].html.twig
      'path' => 'themes/retraitespopulaires' . '/templates/' . $theme,
      'template'  => 'blocks/rp--homepage--highlight'
    ),
  );
}
