<?php

/**
* Theme hook
*/
function rp_layout_theme($existing, $type, $theme, $path) {
    return array(
        // Blocks themes
        // ---------------------------------------------------------------------
        'rp_layout_header_block' => array(
            'variables' => ['variables' => []],
            'path' => 'themes/retraitespopulaires/templates/' . $theme,
            'template'  => 'blocks/header'
        ),
        'rp_layout_skip_nav_links_block' => [
          'variables' => ['variables' => []],
          'path'      => 'themes/retraitespopulaires/templates/' . $theme,
          'template'  => 'blocks/skip_nav_links',
        ],
        'rp_layout_footer_block' => array(
            'variables' => ['variables' => []],
            'path' => 'themes/retraitespopulaires/templates/' . $theme,
            'template'  => 'blocks/footer'
        ),
        'rp_layout_secondarynav_block' => array(
            'variables' => ['variables' => []],
            'path' => 'themes/retraitespopulaires/templates/' . $theme,
            'template'  => 'blocks/secondarynav'
        ),
        'rp_layout_cover_block' => array(
            'variables' => ['variables' => []],
            'path' => 'themes/retraitespopulaires/templates/' . $theme,
            'template'  => 'blocks/cover'
        ),
    );
}
