<?php

/**
* Theme hook
*/
function rp_layout_theme($existing, $type, $theme, $path) {
    return array(
        // Blocks themes
        // ---------------------------------------------------------------------
        'rp_layout_header_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => \Drupal::theme()->getActiveTheme()->getPath() . '/templates/' . $theme,
            'template'  => 'blocks/header'
        ),
        'rp_layout_footer_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => \Drupal::theme()->getActiveTheme()->getPath() . '/templates/' . $theme,
            'template'  => 'blocks/footer'
        ),
        'rp_layout_bigmenu_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => \Drupal::theme()->getActiveTheme()->getPath() . '/templates/' . $theme,
            'template'  => 'blocks/bigmenu'
        ),
        'rp_layout_secondarynav_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => \Drupal::theme()->getActiveTheme()->getPath() . '/templates/' . $theme,
            'template'  => 'blocks/secondarynav'
        ),
        'rp_layout_cover_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => \Drupal::theme()->getActiveTheme()->getPath() . '/templates/' . $theme,
            'template'  => 'blocks/cover'
        ),
    );
}
