<?php

/**
 * @file
 * Contains rp_mortgage.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_mortgage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_mortgage module.
    case 'help.page.rp_mortgage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide Mortgage (Hypothèque) calculator and Rates import') . '</p>';
      return $output;

    default:
  }
}
