<?php

/**
 * @file
 * Contains rp_mortgage.module..
 */

/**
 * Implements hook_theme().
 */
function rp_mortgage_theme($existing, $type, $theme, $path) {
  return [
    // Blocks themes
    // ---------------------------------------------------------------------.
    'rp_mortgage_table_rate_block' => [
      // Use the following syntax to retrieve all variables
      // in the "variables" container.
      'variables' => ['variables' => []],
      // Set the template attribute to force the theme suggestions
      // into a sub folder using [template].html.twig.
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/table_rate',
    ],
    'rp_mortgage_table_hypothec_rate_block' => [
      // Use the following syntax to retrieve all variables
      // in the "variables" container.
      'variables' => ['variables' => []],
      // Set the template attribute to force the theme suggestions
      // into a sub folder using [template].html.twig.
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/table_hypothec_rate',
    ],
    'rp_mortgage_table_building_rate_block' => [
      // Use the following syntax to retrieve all variables
      // in the "variables" container.
      'variables' => ['variables' => []],
      // Set the template attribute to force the theme suggestions
      // into a sub folder using [template].html.twig.
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/table_building_rate',
    ],
    'rp_mortgage_table_company_rate_block' => [
      // Use the following syntax to retrieve all variables
      // in the "variables" container.
      'variables' => ['variables' => []],
      // Set the template attribute to force the theme suggestions
      // into a sub folder using [template].html.twig.
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/table_company_rate',
    ],

    // ---------------------------------------------------------------------.
    'rp_mortgage_calculator_block' => [
      // Use the following syntax to retrieve all variables
      // in the "variables" container.
      'variables' => ['variables' => []],
      // Set the template attribute to force the theme suggestions
      // into a sub folder using [template].html.twig.
      'path' => 'themes/retraitespopulaires/templates/' . $theme,
      'template'  => 'blocks/calculator',
    ],
  ];
}
