<?php

/**
* Theme hook
*/
function rp_offers_theme($existing, $type, $theme, $path) {
    return array(
        // Blocks themes
        // ---------------------------------------------------------------------
        'rp_offers_linked_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => 'themes/retraitespopulaires' . '/templates/' . $theme,
            'template'  => 'blocks/offers_linked'
        ),
        'rp_offers_offer_teaser_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'path' => 'themes/retraitespopulaires' . '/templates/' . $theme,
            'template'  => 'blocks/offer_teaser'
        ),
    );
}
