<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

/**
 * Change the default size of ckeditor height.
 */
function rp_ckeditor_editor_js_settings_alter(array &$settings) {
  foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
    if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
      $settings['editor']['formats'][$text_format_id]['editorSettings']['height'] = '400px';
    }
  }
}
