module:
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_media_embed: 0
  color: 0
  config: 0
  config_translation: 0
  content_translation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  mailsystem: 0
  menu_breadcrumb: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  rdf: 0
  redirect: 0
  rp_ckeditor: 0
  rp_contact: 0
  rp_exchange_rates: 0
  rp_homepage: 0
  rp_layout: 0
  rp_mortgage: 0
  rp_newsletter: 0
  rp_offers: 0
  rp_site: 0
  rp_toolbar: 0
  search_api: 0
  search_api_attachments: 0
  search_api_db: 0
  search_api_solr: 0
  shortcut: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_extender: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  retraitespopulaires: 0
  retraitespopulaires_admin: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: fr
