extraction_method: tika_extractor
preserve_cache: true
solr_extractor_configuration:
  solr_server: solr
  solr_tika_path: update/extract
pdftotext_extractor_configuration: {  }
tika_extractor_configuration:
  java_path: java
  tika_path: /opt/tika/tika-app-1.13.jar
python_pdf2txt_extractor_configuration:
  python_path: python
  python_pdf2txt_script: /usr/bin/pdf2txt
_core:
  default_config_hash: kHI7OlneY7oVu9QZqE_pwrAC_rkWA5b6W-YwMk5vrrQ
langcode: fr
