extraction_method: ''
preserve_cache: true
solr_extractor_configuration:
  solr_server: ''
  solr_tika_path: update/extract
pdftotext_extractor_configuration: {  }
tika_extractor_configuration:
  java_path: java
  tika_path: ''
python_pdf2txt_extractor_configuration:
  python_path: python
  python_pdf2txt_script: /usr/bin/pdf2txt
_core:
  default_config_hash: kHI7OlneY7oVu9QZqE_pwrAC_rkWA5b6W-YwMk5vrrQ
langcode: fr
