settings:
  default_page_base_path: form
  default_form_open_message: 'This form has not yet been opened to submissions.'
  default_form_close_message: 'Sorry...This form is closed to new submissions.'
  default_form_exception_message: 'Unable to display this webform. Please contact the site administrator.'
  default_form_confidential_message: 'This form is confidential. You must <a href="[site:login-url]/logout?destination=[current-page:url:relative]">Log out</a> to submit it.'
  default_form_submit_label: Soumettre
  form_classes: "container-inline clearfix\r\nform--inline clearfix\r\nmessages messages--error\r\nmessages messages--warning\r\nmessages messages--status\r\n"
  button_classes: ''
  default_form_submit_once: false
  default_form_disable_back: false
  default_form_unsaved: false
  default_form_novalidate: false
  default_form_details_toggle: true
  default_submission_log: false
  default_wizard_prev_button_label: '< Previous Page'
  default_wizard_next_button_label: 'Next Page >'
  default_wizard_start_label: Start
  default_wizard_complete_label: Complete
  default_preview_next_button_label: Preview
  default_preview_prev_button_label: '< Previous'
  default_preview_message: 'Please review your submission. Your submission is not complete until you press the "Submit" button!'
  default_draft_button_label: 'Save Draft'
  default_draft_saved_message: 'Submission saved. You may return to this form later and it will restore the current values.'
  default_draft_loaded_message: 'A partially-completed form was found. Please complete the remaining portions.'
  default_confirmation_message: 'New submission added to [webform:title].'
  default_confirmation_back_label: 'Back to form'
  confirmation_classes: "messages messages--error\r\nmessages messages--warning\r\nmessages messages--status\r\n"
  confirmation_back_classes: "button\r\n"
  default_limit_total_message: 'No more submissions are permitted.'
  default_limit_user_message: 'No more submissions are permitted.'
assets:
  css: ''
  javascript: ''
export:
  exporter: delimited
  delimiter: ;
  excel: false
  file_name: 'submission-[webform_submission:serial]'
  multiple_delimiter: ','
  header_format: label
  header_prefix: true
  header_prefix_label_delimiter: ': '
  header_prefix_key_delimiter: __
  composite_element_item_format: label
  options_format: compact
  options_item_format: label
  entity_reference_format: link
  likert_answers_format: label
  signature_format: status
batch:
  default_batch_export_size: 500
  default_batch_update_size: 500
  default_batch_delete_size: 500
purge_settings:
  cron_size: 100
elements:
  allowed_tags: admin
  wrapper_classes: "container-inline clearfix\r\nform--inline clearfix\r\nmessages messages--error\r\nmessages messages--warning\r\nmessages messages--status\r\n"
  classes: "container-inline clearfix\r\nform--inline clearfix\r\nmessages messages--error\r\nmessages messages--warning\r\nmessages messages--status\r\n"
  default_description_display: ''
  default_icheck: ''
  default_google_maps_api_key: ''
  excluded_types:
    captcha: captcha
    color: color
    container: container
    date: date
    datelist: datelist
    datetime: datetime
    details: details
    entity_autocomplete: entity_autocomplete
    item: item
    label: label
    language_select: language_select
    machine_name: machine_name
    managed_file: managed_file
    number: number
    password: password
    password_confirm: password_confirm
    range: range
    search: search
    select: select
    table: table
    tableselect: tableselect
    tel: tel
    text_format: text_format
    url: url
    value: value
    webform_address: webform_address
    webform_audio_file: webform_audio_file
    webform_autocomplete: webform_autocomplete
    webform_buttons: webform_buttons
    webform_buttons_other: webform_buttons_other
    webform_checkboxes_other: webform_checkboxes_other
    webform_codemirror: webform_codemirror
    webform_contact: webform_contact
    webform_creditcard: webform_creditcard
    webform_creditcard_number: webform_creditcard_number
    webform_document_file: webform_document_file
    webform_element: webform_element
    webform_email_confirm: webform_email_confirm
    webform_email_multiple: webform_email_multiple
    webform_entity_checkboxes: webform_entity_checkboxes
    webform_entity_radios: webform_entity_radios
    webform_entity_select: webform_entity_select
    webform_flexbox: webform_flexbox
    webform_image_file: webform_image_file
    webform_link: webform_link
    webform_location: webform_location
    webform_message: webform_message
    webform_name: webform_name
    webform_radios_other: webform_radios_other
    webform_rating: webform_rating
    webform_select_other: webform_select_other
    webform_signature: webform_signature
    webform_table_sort: webform_table_sort
    webform_tableselect_sort: webform_tableselect_sort
    webform_telephone: webform_telephone
    webform_term_select: webform_term_select
    webform_time: webform_time
    webform_toggle: webform_toggle
    webform_toggles: webform_toggles
    webform_video_file: webform_video_file
    webform_wizard_page: webform_wizard_page
file:
  file_public: false
  default_max_filesize: ''
  default_managed_file_extensions: 'gif jpg png bmp eps tif pict psd txt rtf html odf pdf doc docx ppt pptx xls xlsx xml avi mov mp3 ogg wav bz2 dmg gz jar rar sit svg tar zip'
  default_audio_file_extensions: 'mp3 ogg wav'
  default_document_file_extensions: 'txt rtf pdf doc docx odt ppt pptx odp xls xlsx ods'
  default_image_file_extensions: 'gif jpg png svg'
  default_video_file_extensions: 'avi mov mp4 ogg wav webm'
format:
  webform_likert:
    item: table
mail:
  roles: {  }
  default_from_mail: '[site:mail]'
  default_from_name: '[site:name]'
  default_reply_to: ''
  default_return_path: ''
  default_subject: 'Webform submission from: [webform_submission:source-entity]'
  default_body_text: "Submitted on [webform_submission:created]\r\nSubmitted by: [webform_submission:user]\r\n\r\nSubmitted values are:\r\n[webform_submission:values]\r\n"
  default_body_html: "<p>Submitted on [webform_submission:created]</p>\r\n<p>Submitted by: [webform_submission:user]</p>\r\n<p>Submitted values are:</p>\r\n[webform_submission:values]\r\n"
test:
  types: "checkbox:\r\n  - true\r\ncolor:\r\n  - '#ffffcc'\r\n  - '#ffffcc'\r\n  - '#ccffff'\r\ndate:\r\n  - '1942-06-18'\r\n  - '1940-07-07'\r\n  - '1943-02-25'\r\n  - '1940-10-09'\r\ndatetime:\r\n  - '1942-06-18'\r\n  - '1940-07-07'\r\n  - '1943-02-25'\r\n  - '1940-10-09'\r\ndatelist:\r\n  - '1942-06-18'\r\n  - '1940-07-07'\r\n  - '1943-02-25'\r\n  - '1940-10-09'\r\nemail:\r\n  - 'example@example.com'\r\n  - 'test@test.com'\r\n  - 'random@random.com'\r\nlanguage_select:\r\n  - en\r\nmachine_name:\r\n  - 'loremipsum'\r\n  - 'oratione'\r\n  - 'dixisset'\r\ntel:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ntextarea:\r\n  - 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Negat esse eam, inquit, propter se expetendam. Primum Theophrasti, Strato, physicum se voluit; Id mihi magnum videtur. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere.'\r\n  - 'Huius, Lyco, oratione locuples, rebus ipsis ielunior. Duo Reges: constructio interrete. Sed haec in pueris; Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Sapiens autem semper beatus est et est aliquando in dolore; Immo videri fortasse. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Et ille ridens: Video, inquit, quid agas;'\r\n  - 'Quae cum dixisset, finem ille. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Gloriosa ostentatio in constituendo summo bono. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Duarum enim vitarum nobis erunt instituta capienda. Comprehensum, quod cognitum non habet? Qui enim existimabit posse se miserum esse beatus non erit. Causa autem fuit huc veniendi ut quosdam hinc libros promerem. Nunc omni virtuti vitium contrario nomine opponitur.'\r\ntext_format:\r\n  - value: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Negat esse eam, inquit, propter se expetendam. Primum Theophrasti, Strato, physicum se voluit; Id mihi magnum videtur. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere.</p>'\r\n  - value: '<p>Huius, Lyco, oratione locuples, rebus ipsis ielunior. Duo Reges: constructio interrete. Sed haec in pueris; Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Sapiens autem semper beatus est et est aliquando in dolore; Immo videri fortasse. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Et ille ridens: Video, inquit, quid agas;</p>'\r\n  - value: '<p>Quae cum dixisset, finem ille. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Gloriosa ostentatio in constituendo summo bono. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Duarum enim vitarum nobis erunt instituta capienda. Comprehensum, quod cognitum non habet? Qui enim existimabit posse se miserum esse beatus non erit. Causa autem fuit huc veniendi ut quosdam hinc libros promerem. Nunc omni virtuti vitium contrario nomine opponitur.</p>'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\nwebform_creditcard_number:\r\n  - '4111111111111111'\r\nwebform_email_confirm:\r\n  - 'example@example.com'\r\n  - 'test@test.com'\r\n  - 'random@random.com'\r\nwebform_email_multiple:\r\n  - 'example@example.com, test@test.com, random@random.com'\r\nwebform_location:\r\n  - value: 'The White House, 1600 Pennsylvania Ave NW, Washington, DC 20500, USA'\r\n  - value: 'London SW1A 1AA, United Kingdom'\r\n  - value: 'Moscow, Russia, 10307'\r\nwebform_time:\r\n  - '09:00'\r\n  - '17:00'\r\n"
  names: "first_name:\r\n  - 'John'\r\n  - 'Paul'\r\n  - 'Ringo'\r\n  - 'George'\r\nlast_name:\r\n  - 'Lennon'\r\n  - 'McCartney'\r\n  - 'Starr'\r\n  - 'Harrison'\r\naddress:\r\n  - '10 Main Street'\r\n  - '11 Brook Alley Road. APT 1'\r\nzip:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\nphone:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ncity:\r\n  - 'Springfield'\r\n  - 'Pleasantville'\r\n  - 'Hill Valley'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\ndefault:\r\n  - 'Loremipsum'\r\n  - 'Oratione'\r\n  - 'Dixisset'\r\n"
ui:
  video_display: dialog
  details_save: true
  dialog_disabled: false
  offcanvas_disabled: false
  html_editor_disabled: false
libraries:
  excluded_libraries:
    - jquery.chosen
  cdn: false
langcode: fr
third_party_settings: {  }
