---
title: Actions Bar
name: actions-bar
collection: molecules
notes: |
---
<div class="actions-bar">
  <h2 class="h4 actions-bar-title">1 rubrique, 13 éléments</h2>
  <div class="actions">
    <a href="#" class="btn btn-primary btn-xs">Ajouter un document</a>
    <a href="#" class="btn btn-primary btn-xs">Ajouter une sous-rubrique</a>
    <a href="#" class="btn btn-outline btn-xs">Modifier</a>
  </div>
</div>
