---
title: big-menu-secondary-nav
name: big-menu-secondary-nav
collection: molecules
notes: |
  ##### Usage : `big-menu-secondary-nav`
---
<div class="big-menu-secondary-nav-wrapper">
  <div class="big-menu-secondary-nav visible-xs visible-sm">
    <div class="row">
      <div class="spacer spacer-sm"></div>
      <div class="col-xs-6">
        <ul class="list-no-style text-right">
          <li><a class="pretty-link pretty-link-berrylight-gray" href="#">À propos</a></li>
          <li><a class="pretty-link pretty-link-berrylight-gray" href="#">Contact</a></li>
          <li><a class="pretty-link pretty-link-berrylight-gray" href="#">Actualités</a></li>
        </ul>
      </div>
      <div class="col-xs-6">
        <ul class="list-no-style list-no-padding">
        <li><a class="pretty-link pretty-link-berrylight-gray" href="#">Press</a></li>
        <li><a class="pretty-link pretty-link-berrylight-gray" href="#">Emplois</a></li>
        <li><a class="pretty-link pretty-link-berrylight-gray" href="#">Connexion <i class="fa fa-lock"></i></a></li>
        </ul>
      </div>
      <div class="spacer"></div>
    </div>
  </div>
  <ul class="list-spaced list-no-style list-no-padding hidden-xs hidden-sm" role="navigation">
    <li><a class="pretty-link" href="#">À propos</a></li>
    <li><a class="pretty-link" href="#">Contact</a></li>
    <li><a class="pretty-link" href="#">Actualités</a></li>
    <li><a class="pretty-link" href="#">Press</a></li>
    <li><a class="pretty-link" href="#">Emplois</a></li>
    <li><a class="pretty-link" href="#">Connexion <i class="text-primary fa fa-lock"></i></a></li>
    <li><a class="pretty-link" href="#">FAQ</a></li>
  </ul>
</div>
