---
title: big-menu-secondary-nav
name: big-menu-secondary-nav
collection: molecules
notes: |
  ##### Usage : `big-menu-secondary-nav`
---
<div class="big-menu-secondary-nav-wrapper visible-xs visible-sm">
  <div class="big-menu-secondary-nav">
    <div class="row">
      <div class="spacer"></div>
      <div class="col-xs-6">
        <ul class="unstyled-list text-right">
          <li><a class="pretty-link-white" href="#">À propos</a></li>
          <li><a class="pretty-link-white" href="#">Contact</a></li>
          <li><a class="pretty-link-white" href="#">Actualités</a></li>
        </ul>
      </div>
      <div class="col-xs-6">
        <ul class="unstyled-list">
        <li><a class="pretty-link-white" href="#">Press</a></li>
        <li><a class="pretty-link-white" href="#">Emplois</a></li>
        <li><a class="pretty-link-white" href="#">FAQ</a></li>
        </ul>
      </div>
      <div class="col-xs-12">
        <div class="spacer"></div>
        <div class="text-center">
          <div class="button-bubble button-bubble-white">
            <div class="bubble-icon">
              <a href="#"><i class="retraitespopulaires-icon retraitespopulaires-icon-3x retraitespopulaires-icon-lock"></i></a>
            </div>
            <div class="bubble-link">
              <a href="#" class="pretty-link-white">Connexion</a>
            </div>
          </div>
        </div>
        <div class="spacer"></div>
      </div>
    </div>
  </div>
</div>
