---
title: big-menu
name: big-menu
collection: molecules
notes: |
  ##### Usage : `big-menu`
---
<div class="big-menu">
  <div class="container-big-menu">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          SEARCH
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 big-menu-wrapper-profils">
          <div class="">PROFIL</div>
        </div>
        <div class="col-md-8 big-menu-wrapper-nav">
          <div class="row big-menu-wrapper-professions">
            <div class="col-md-3">1</div>
            <div class="col-md-3">2</div>
            <div class="col-md-3">3</div>
            <div class="col-md-3">4</div>
          </div>
          <div class="row big-menu-wrapper-shortcuts">
            <div class="col-xs-12">Shortcuts</div>
          </div>
          <div class="row big-menu-wrapper-contact">
            <div class="big-menu-wrapper-contact-info">
              <div class="col-xs-4">Contact Info</div>
              <div class="col-xs-4">Contact Info</div>
              <div class="col-xs-4">Contact Info</div>
            </div>
            <div class="big-menu-wrapper-contact-places">
              <div class="col-xs-4">Places</div>
              <div class="col-xs-4">Places</div>
              <div class="col-xs-4">Places</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
