---
title: breadcrumb-rpjeune
name: breadcrumb-rpjeune
collection: molecules
notes: |
  ##### Usage : `breadcrumb-rpjeune`
  ##### Options :
  - **option** - Type
---
<div class="breadcrumb">
  <ul class="list-inline list-no-style list-no-padding">
    <li class="text-primary">Accueil</li>
    <li class="text-muted">›</li>
    <li class="text-assurance">Assurance vie</li>
    <li class="text-muted">›</li>
    <li class="text-muted">RP Jeune</li>
  </ul>
</div>