---
title: card-attachement-rp-jeune
name: card-attachement-rp-jeune
collection: molecules
notes: |
  ##### Usage : `card-attachement-rp-jeune`
  ##### Options :
  - **theme** - String
---
<div class="card-attachement card-attachement-{{theme}} shadow shadow-down">
  <div class="card-title h2">Questions fréquentes</div>
  <ul class="card-content list-spaced list-unstyled">
    <li><a class="text-bold pretty-link h5" href="#">Qu’est-ce qu’un 3e pilier A ou prévoyance liée?</a></li>
    <li><a class="text-bold pretty-link h5" href="#">Comment maintenir son niveau de vie à la retraite?</a></li>
    <li><a class="text-bold pretty-link h5" href="#">Qu'en est-il du 3e pilier en cas de divorce?</a></li>
  </ul>
  <div class="card-footer">
    <div class="media">
    <div class="media-left">
        <a href="#" class="retraitespopulaires-icon retraitespopulaires-icon-placeholder"></a>
    </div>
    <div class="media-body">
      <a class="text-bold pretty-link h5" href="#">Accéder à toutes les questions sur l'assurance vie</a>
    </div>
    </div>
  </div>
</div>