---
title: card-attachement
name: card-attachement
collection: molecules
notes: |
  ##### Usage : `card-attachement`
  ##### Options :
  - **theme** - String
---
<div class="card-attachement card-attachement-{{theme}} shadow shadow-down">
  <div class="card-title h2">Questions fréquentes</div>
  <ul class="card-content list-spaced list-unstyled">
    <li><a class="text-bold pretty-link h5" href="#">Interdum et</a></li>
    <li><a class="text-bold pretty-link h5" href="#">Aenean sollicitudin quis est a sollicitudin - Donec faucibus at mauris</a></li>
    <li><a class="text-bold pretty-link h5" href="#">Interdum et</a></li>
    <li><a class="text-bold pretty-link h5" href="#">Lorem ipsum dolor sit amet</a></li>
  </ul>
  <div class="card-footer">
    <div class="media">
    <div class="media-left">
        <a href="#" class="retraitespopulaires-icon retraitespopulaires-icon-placeholder"></a>
    </div>
    <div class="media-body">
      <a class="text-bold pretty-link h5" href="#">Accéder à toutes les questions sur l'assurance vie</a>
    </div>
    </div>
  </div>
</div>
