---
title: collapse
name: collapse
collection: molecules
notes: |
  ##### Usage : `collapse`
---
<div class="collapse-wrapper">
  <div class="collapse-title">
    <h5 class="inline-block">
      <a href="#">Assurance vie</a>
    </h5>
    <a class="inline-block pull-right" role="button" data-toggle="collapse" href="#assurance-vie" aria-expanded="true" aria-controls="assurance-vie">
      <i class="retraitespopulaires-icon retraitespopulaires-icon-angle"></i>
    </a>
    <div class="clearfix"></div>
  </div>
  <div id="assurance-vie" class="collapse-body collapse in">
    <ul class="unordered-list">
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
      <li>RP</li>
    </ul>
  </div>
</div>
