---
title: Document card
name: document-card
collection: molecules
---
<div class="document-card">
  <span class="document-card-icon retraitespopulaires-icon retraitespopulaires-icon-3x retraitespopulaires-icon-document-file"></span>
  <div class="document-card-content">
    <div class="document-card-text">
      <a href="#"><h3 class="document-card-title">	Analyse des résultats 2011 des caisses de pension publiques romandes</h3></a>
      <p class="document-card-subtitle">Villa - Prêt hypothécaire</p>
      <small class="document-card-number text-muted">No200737.1</small>
    </div>
    <a class="document-card-btn btn btn-primary btn-outline" href="#">Consulter</a>
  </div>
</div>
