---
title: dropdown
name: dropdown
bootstrap: http://getbootstrap.com/javascript/#dropdowns
notes: |
  Can be wrapped in `.theme-[theme]` to change look.
collection: molecules
---
<div class="dropdown open">
  <a href="#" class="dropdown-toggle btn btn-primary" id="drop5" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    Dropdown <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" id="menu2" aria-labelledby="drop5">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>
