---
title: mandats-contact
name: mandats-contact
collection: molecules
notes: |
  ##### Usage : `mandats-contact`
  ##### Options :
  - **option** - Type
---
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#lausanne" aria-controls="lausanne" role="tab" data-toggle="tab">Lausanne (siège)</a></li>
</ul>
<div class="spacer spacer-sm"></div>
<div class="row">
  <div class="col-xs-12">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="lausanne">
        <a href="tel:+41213482111" class="text-large text-no-wrap d-block pretty-link text-cip">021 348 24 51</strong></a>
        <a href="mailto:info@cipvd.ch " class="text-large d-block pretty-link text-cip">info@cipvd.ch </a>
      </div>
    </div>
  </div>
</div>
