---
title: mandats-contact
name: mandats-contact
collection: molecules
notes: |
  ##### Usage : `mandats-contact`
  ##### Options :
  - **option** - Type
---
<h4>Lausanne (siège)</h4>

<div class="spacer spacer-sm"></div>

<div class="row">
  <div class="col-xs-12">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="lausanne">
        <a href="tel:+41213482111" class="text-large text-no-wrap d-block">021 348 21 11</a>
        <a href="mailto:info@retraitespopulaires.ch" class="text-large d-block">info@cip.ch</a>
      </div>
    </div>
  </div>
</div>
