---
title: Big Menu Secondary Nav
name: menu-secondary-nav
collection: molecules
notes: |
  ##### Usage : `menu-secondary-nav`
  - **big_menu_secondary_nav_theme** - <b>['primary'|'assurance'|'prevoyance'|'immobilier'|'hypotheque'|'institutionnel'|'profelia'|'cpev'|'cip']</b>

---
<div class="bg-berrylight-gray">
  <div class="container">
    <div class="spacer"></div>
    <div class="col-xs-12">
      <ul class="list-no-style list-no-padding two-cols">
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="/a-propos">À propos</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="/documents-utiles">Documents</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="/questions-reponses">FAQ</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="/offres">Offres Bella vita</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="/emploi">Emploi</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="spacer"></div>
</div>
