---
title: Secondary Nav
name: menu-secondary-nav
collection: molecules
notes: |
  Can be wrapped in `.theme-[theme]` to change look. <br />
  This component is visible into the [basic page](/basic-page).
---
<div class="bg-berrylight-gray">
  <div class="container">
    <div class="spacer"></div>
    <div class="col-xs-12">
      <ul class="list-no-style list-no-padding two-cols">
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="#">À propos</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="#">Documents</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="#">FAQ</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="#">Offres Bella vita</a>
        </li>
        <li class="m-b-1">
          <a class="pretty-link pretty-link-berrylight-gray" href="#">Emploi</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="spacer"></div>
</div>
