---
title: navbar
name: navbar
collection: molecules
notes: |
  Can be wrapped in `.theme-[theme]` to change look.
---
<nav class="navbar" id="bs-example-navbar-collapse-1" aria-label="Navigation principale">
  <ul class="list-unstyled m-0">
    <li><a href="#">Prévoyance</a></li>
    <li class="active">
      <a href="#main-content"><span class="sr-only">Page active</span> Immobilier</a>
    </li>
    <li><a href="#">Prêts</a></li>
    <li><a href="#">Actualités <span class="sr-only">(current)</span></a></li>
    <li><a href="#">CIP</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
</nav>
