---
title: Prenavbar
name: prenavbar
collection: molecules
notes: |
  Can be wrapped in `.theme-[theme]` to change look
---
<ul class="prenavbar list-unstyled list-inline m-0" id="secondary-navigation" role="navigation" aria-label="Navigation secondaire">
  <li>
    <a href="/a-propos" class="text-muted small " target="">À propos</a>
  </li>
  <li>
    <a href="/documents-utiles" class="text-muted small " target="">Documents</a>
  </li>
  <li>
    <a href="/questions-reponses" class="text-muted small " target="">FAQ</a>
  </li>
  <li>
    <a href="/offres" class="text-muted small " target="">Offres Bella vita</a>
  </li>
  <li>
    <a href="/emploi" class="text-muted small " target="">Emploi</a>
  </li>
</ul>
