---
title: Prenavbar
name: prenavbar
collection: molecules
notes: |
  Can be wrapped in `.theme-[theme]` to change look. <br />
  **This component is visible on the [basic page](/basic-page)**.
---
<ul class="prenavbar list-unstyled list-inline m-0" id="secondary-navigation" role="navigation" aria-label="Navigation secondaire">
  <li>
    <a href="#" class="text-muted small" target="">À propos</a>
  </li>
  <li>
    <a href="#" class="text-muted small" target="">Déjà client</a>
  </li>
  <li>
    <a href="#" class="text-muted small" target="">Connexion</a>
  </li>
  <li>
    <a href="#" class="text-muted small" target="">Emploi</a>
  </li>
  <li>
    <a href="#" class="text-muted small" target="">Contact/aide</a>
  </li>
</ul>
