---
title: Progresschart
name: progresschart
bootstrap: https://getbootstrap.com/components/#progress
collection: molecules
notes: |
  Can be wrapped in `.theme-[theme]` to change look
---
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%;">95%</div>
  <div class="progress-pipe" role="progresspipe" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"></div>
</div>
