---
title: progresschart
name: progresschart
collection: molecules
notes: |
  Can be wrapped in `.theme-[theme]` to change look

---

<h2>Visualisation</h2>
<div class="spacer"></div>

<h4>Financement hypothécaire nécessaire (max 80%)</h4>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width: 95%;">
  95%
  </div>
  <div class="progress-pipe" role="progresspipe" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"></div>
</div>
<small>Contactez-nous</small>

<h4>Charge hypothécaire annuelle (max 33%)</h4>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="48" aria-valuemin="0" aria-valuemax="100" style="width: 48%;">
    48%
  </div>
  <div class="progress-pipe" role="progresspipe" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
</div>
