---
title: Push Menu
name: push-menu
collection: molecules
notes: |
  Responsive tray for mobile. Specially used as mobile main navigation.
---
<nav class="push-menu" aria-label="Navigation principale - Mobile">
  <ul class="list-unstyled m-b-1 main-navigation">
    <li><a class="h3" href="#">Prévoyance</a></li>
    <li class="active">
      <a class="h3" href="#main-content"><span class="sr-only">Page active</span> Immobilier</a>
    </li>
    <li><a class="h3" href="#">Prêts</a></li>
    <li><a class="h3" href="#">Actualités</a></li>
    <li><a class="h3" href="#">CIP</a></li>
    <li><a class="h3" href="#">Contact</a></li>
  </ul>

  <ul class="prenavbar list-unstyled m-0 secondary-navigation" role="navigation" aria-label="Navigation d'en-tête">
    <li class="active">
      <a href="#" class="active h6" target=""><span class="sr-only">Page active</span> Contact</a>
    </li>
    <li>
      <a href="#" class="h6" target="">Presse</a>
    </li>
    <li>
      <a href="#" class="h6" target="">Extranet</a>
    </li>
  </ul>
</nav>
