---
title: search-form
name: search-form
collection: molecules
notes: |
  ##### Usage : `search-form`
---
<form class="global-search">
    <label class="label-hidden"></label>
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Chercher un produit, un document, un contact, ...">
      <span class="input-group-btn">
        <button class="btn btn-default btn-icon" type="button"><i class="retraitespopulaires-icon retraitespopulaires-icon-search"></i></button>
      </span>
    </div>
</form>
