---
title: secondary-nav
name: secondary-nav
collection: molecules
notes: |
  ##### Usage : `secondary-nav`
---
<div class="secondary-nav">
  <div class="back">
    <a href="#" class="retraitespopulaires-icon retraitespopulaires-icon-arrow"></a>
  </div>
  <div class="secondary-nav-content">
    <div class="title h5 text-cocon">Assurance Vie</div>
    <ul class="links list-no-style list-no-padding">
      <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
      <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
      <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
      <li class="active"><a class="pretty-link" href="#">Aliquam placerat</a></li>
      <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
      <li><a class="pretty-link text-bold" href="#">Gestion de mandats</a>
        <ul class="list-no-style list-no-padding">
          <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
          <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
          <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
          <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
          <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
        </ul>
      </li>
      <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
      <li><a class="pretty-link" href="#">Aliquam placerat</a></li>
    </ul>
  </div>
</div>
