---
title: secondary-nav-plp
name: secondary-nav-plp
collection: molecules
notes: |
  ##### Usage : `secondary-nav-plp`
  ##### Options :
  - **theme** - String
---
<div class="secondary-nav secondary-nav-{{ theme }}">
  <div class="back">
    <a href="retraitespopulaires-styleguide/particuliers" class="retraitespopulaires-icon retraitespopulaires-icon-arrow"></a>
  </div>
  <div class="secondary-nav-content">
    <div class="title h5 text-cocon">Prévoyance professionnelle</div>
    <ul class="links list-no-style list-no-padding">
      <li><a class="pretty-link" href="#">Assurer les employés</a></li>
      <li><a class="pretty-link" href="#">Plans complémentaires</a></li>
      <li><a class="pretty-link" href="#">Associations professionnelles</a></li>
      <li><a class="pretty-link" href="#">Gestion de mandats</a></li>
      <li><a class="pretty-link" href="#">Diagnostic gratuit</a></li>
      <li><a class="pretty-link" href="#">Déjà assuré?</a></li>
      <li><a class="pretty-link" href="#">Indépendants</a></li>
      <li><a class="pretty-link" href="#">Transiter entre deux emplois</a></li>
      <li>
        <ul class="list-no-style list-no-padding">
          <li class="active"><a class="pretty-link text-bold" href="#">Simulateur pour une police de libre passage</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>