---
title: secondary-nav-assurance
name: secondary-nav-assurance
collection: molecules
notes: |
  ##### Usage : `secondary-nav-assurance`
  ##### Options :
  - **theme** - String
---
<div class="secondary-nav secondary-nav-{{ theme }}">
  <div class="back">
    <a href="retraitespopulaires-styleguide/assurance-vie" class="retraitespopulaires-icon retraitespopulaires-icon-arrow"></a>
  </div>
  <div class="secondary-nav-content">
    <div class="title h5 text-cocon">Assurance vie</div>
    <ul class="links list-no-style list-no-padding">
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Rente immédiate</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Rente immédiate certaine</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Rente différée</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Jeune</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Duo primes périodiques</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP RDuo prime unique</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Épargne</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Refuge</a></li>
      <li><a class="pretty-link" href="retraitespopulaires-styleguide/rp-jeune">RP Sécurifonds</a></li>
    </ul>
  </div>
</div>