---
title: secondary-nav-rpjeune
name: secondary-nav-rpjeune
collection: molecules
notes: |
  ##### Usage : `secondary-nav-rpjeune`
  ##### Options:
  - **theme** - String
---
<div class="secondary-nav secondary-nav-{{ theme }}">
  <div class="back">
    <a href="#" class="retraitespopulaires-icon retraitespopulaires-icon-arrow"></a>
  </div>
  <div class="secondary-nav-content">
    <div class="title h5 text-cocon">Assurance Vie</div>
    <ul class="links list-no-style list-no-padding">
      <li><a class="pretty-link" href="#">RP Rente immédiate</a></li>
      <li><a class="pretty-link" href="#">RP Rente immédiate certaine</a></li>
      <li><a class="pretty-link" href="#">RP Rente différée</a></li>
      <li class="active">RP Jeune</li>
      <li><a class="pretty-link" href="#">RP Duo primes périodiques</a></li>
      <li><a class="pretty-link" href="#">RP Duo primes uniques</a></li>
      <li><a class="pretty-link" href="#">RP Épargne</a></li>
      <li><a class="pretty-link" href="#">RP Refuge</a></li>
      <li><a class="pretty-link" href="#">RP Securifonds</a></li>
    </ul>
  </div>
</div>