---
title: Selectize
name: selectize
collection: molecules
---
<div class="form-group">
  <label for="edit-keyword" class="control-label form-control-label">Mots-clés</label>
  <select selectize class="selectize" data-options="[{&quot;name&quot;:&quot;Actions&quot;},{&quot;name&quot;:&quot;ass&quot;},{&quot;name&quot;:&quot;Assureurs priv\u00e9s&quot;},{&quot;name&quot;:&quot;Courtiers&quot;}]" multiple="multiple" id="edit-keyword">
    <option>Actions</option>
    <option>ass</option>
    <option>Assureurs privés</option>
    <option>Courtiers</option>
  </select>
</div>
