---
title: tabs
name: tabs
collection: molecules
notes: |
  ##### Usage : `tabs`
---
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#lausanne" aria-controls="lausanne" role="tab" data-toggle="tab">Lausanne (siège)</a></li>
  <li role="presentation"><a href="#yverdon" aria-controls="yverdon" role="tab" data-toggle="tab">Yverdon-les-Bains</a></li>
  <li role="presentation"><a href="#nyon" aria-controls="nyon" role="tab" data-toggle="tab">Nyon</a></li>
</ul>

<div class="spacer spacer-sm"></div>

<div class="row">
  <div class="col-xs-12">
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="lausanne">
        <a href="tel:+41213482111" class="text-large">021 348 <strong>21 11</strong></a>
      </div>
      <div role="tabpanel" class="tab-pane" id="yverdon">
        <a href="tel:+41213482821" class="text-large">021 348 <strong>28 21</strong></a>
      </div>
      <div role="tabpanel" class="tab-pane" id="nyon">
        <a href="tel:+41213482020" class="text-large">021 348 <strong>20 20</</strong></a>
      </div>
    </div>
  </div>
</div>
