---
title: teaser-collectivites
name: teaser-collectivites
collection: molecules
notes: |
  ##### Usage : `teaser-collectivites`
---
<div class="teaser-basicpage shadow shadow-down">
  <div class="basicpage-heading">
    <div class="text-primary icon-text icon-text-center">
      <span class="retraitespopulaires-icon retraitespopulaires-icon-placeholder retraitespopulaires-icon-2x"></span> <a href="#" class="icon-text-txt text-cocon h4">Collectivités</a>
    </div>
  </div>
  <div class="basicpage-body">
    <p>Notre gestion d'institutions de prévoyance vous intéressera sûrement ! Nous finançons également la construction de nouvelles infrastructures et de logements.</p>
  </div>
</div>