---
title: teaser-basicpage
name: teaser-basicpage
collection: molecules
notes: |
  ##### Usage : `teaser-basicpage`
---
<div class="teaser-basicpage shadow shadow-down">
  <div class="basicpage-heading">
    <div class="text-primary icon-text icon-text-center">
      <span class="retraitespopulaires-icon retraitespopulaires-icon-placeholder retraitespopulaires-icon-2x"></span> <a href="#" class="icon-text-txt text-cocon h4">Particuliers</a>
    </div>
  </div>
  <div class="basicpage-body">
    <p>Vous trouverez chez nous de précieux renseignements sur la prévoyance professionnelle et l’assurance vie. Nous avons également des locaux commerciaux à louer.</p>
  </div>
</div>
