---
title: teaser-offer
name: teaser-offer
collection: molecules
notes: |
  ##### Usage : `teaser-offer`
  ##### Options :
  - **theme** - String
---
<div class="teaser-offer shadow shadow-down">
  <div class="offer-heading" style="background-image: url(https://unsplash.it/1400/780)"></div>
  <div class="offer-body">
    <a href="#" class="offer-title h1 pretty-link">Festival Lavaux Classic</a>
    <div class="spacer spacer-sm"></div>

    <div class="offer-extra">
      <div class="pull-left offer-date">
        <div>Décembre 2015</div>
      </div>
      <div class="pull-right offer-infos">
        <div>150 tickets</div>
        <div>Se termine dans 5 jours</div>
      </div>
    </div>
  </div>
</div>
