---
title: teaser-particulier
name: teaser-particulier
collection: molecules
notes: |
  ##### Usage : `teaser-particulier`
  ##### Options :
  - **option** - Type
---
<div class="teaser-basicpage shadow shadow-down">
  <div class="basicpage-heading">
    <div class="text-primary icon-text icon-text-center">
      <span class="retraitespopulaires-icon retraitespopulaires-icon-placeholder retraitespopulaires-icon-2x"></span> <a href="#" class="icon-text-txt text-cocon h4">Particuliers</a>
    </div>
  </div>
  <div class="basicpage-body">
    <p>Retraites Populaires peut vous aider. Que ce soit pour votre épargne, votre famille, votre avenir professionnel, votre retraite ou même votre logement, nous avons des solutions</p>
  </div>
</div>