---
title: teaser-contact
name: teaser-contact
collection: molecules
notes: |
  ##### Usage : `teaser-contact`
---
<div class="teaser-contact shadow shadow-down">
  <div class="contact-heading" style="background-image: url(https://unsplash.it/1400/780)"></div>
  <div class="contact-body">
    <p>N'hésitez pas à nous contacter au <a href="tel:0213482626">021 348 26 26</a>.</p>
    <hr />
    <p>Ou retrouvez votre contact régional en entrant votre code postal<p>
    <form class="form-inline">
      <div class="form-group">
        <input class="form-control" id="zip" type="text" placeholder="Votre NPA"></input>
      </div>
      <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Trouver"></input>
      </div>
    </form>
  </div>
</div>
