---
title: teaser-institution
name: teaser-institution
collection: molecules
notes: |
  ##### Usage : `teaser-institution`
  ##### Options :
  - **logo** - String
---
<a href="#" class="teaser teaser-fullclick teaser-institution teaser-institution shadow shadow-down">
  <div class="institution-heading">
    <img class="img-responsive" src="{{ logo|default('https://3.bp.blogspot.com/-AJNG3A2-QIw/VjTFNFpJjsI/AAAAAAAAACQ/3lkytAva6oY/s600-c/NoImage.png') }}" alt="Logo de l'institution">
  </div>
  <div class="institution-body">
    <div class="institution-title h1 pretty-link">Caisse de pensions de l'Etat de Vaud (CPEV)</div>
    <div class="spacer spacer-sm"></div>
    <p class="m-b--">Gérée par Retraites Populaires</p>
  </div>
</a>
