---
title: teaser-rental
name: teaser-rental
collection: molecules
notes: |
  ##### Usage : `teaser-rental`
---
<div class="teaser-rental shadow shadow-down">
  <div class="rental-heading" style="background-image: url(https://unsplash.it/1400/780)"></div>
  <div class="rental-body">
    <a href="#" class="rental-type h1 pretty-link text-immobilier">Appartement</a>
    <div class="spacer spacer-xs"></div>
    <a href="#" class="rental-title h1 pretty-link text-immobilier">Av. Collonges 12, 1004 Lausanne</a>
    <div class="spacer spacer-sm"></div>
    <div class="row info">
      <div class="col-sm-6 info-property">
        <div>3.5 pièces(s)</div>
        <div>±64m<sup>2</sup></div>
      </div>
      <div class="col-sm-6 info-rent">
        <div>Loyer total</div>
        <div>1'710.-</div>
      </div>
    </div>
  </div>
</div>
