label: Backerymails
description: Backerymails
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        id:
          label: 'Entity ID'
          separator: ', '
        created:
          label: 'Sended at'
          separator: ', '
        module:
          label: Module
          separator: ', '
        module_key:
          label: Key
          separator: ', '
        mail_from:
          label: From
          separator: ', '
        mail_reply_to:
          label: Reply-to
          separator: ', '
        langcode:
          label: Lang
          separator: ', '
        subject:
          label: Subject
          separator: ', '
      title: Mails
      empty:
        area_text_custom:
          content: 'No content available.'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Mails
        description: 'Mails list'
