title: Contact
description: 'Basic email contact webform.'
elements: "name:\n  '#title': 'Your Name'\n  '#type': textfield\n  '#required': true\n  '#default_value': '[webform-authenticated-user:display-name]'\nemail:\n  '#title': 'Your Email'\n  '#type': email\n  '#required': true\n  '#default_value': '[webform-authenticated-user:mail]'\nsubject:\n  '#title': Subject\n  '#type': textfield\n  '#required': true\n  '#test': 'Testing contact webform from [site:name]'\nmessage:\n  '#title': Message\n  '#type': textarea\n  '#required': true\n  '#test': 'Please ignore this email.'\n"
settings:
  form_submit_label: 'Send message'
  confirmation_message: 'Your message has been sent.'
handlers:
  email_confirmation:
    label: 'Email confirmation'
    settings:
      from_name: default
      subject: '[webform_submission:values:subject:value]'
      body: '[webform_submission:values:message:value]'
  email_notification:
    label: 'Email notification'
    settings:
      from_name: '[webform_submission:values:name:value]'
      subject: '[webform_submission:values:subject:value]'
      body: '[webform_submission:values:message:value]'
